version: '2'
services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
     - "8190:8190"
    environment:
      PORT: "8190"
      #
      SESSION_KEY:
      #
      OAUTH_DOMAIN:
      OAUTH_CLIENT_ID:
      OAUTH_CLIENT_SECRET:
      OAUTH_CALLBACK_URL:
      OAUTH_AUDIENCE:
  notes:
    build:
      context: ./notes
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
     - "8191:8191"
    environment:
      PORT: "8191"
